reference_models:
  - name: "Qwen/Qwen2-7B-Instruct"
    api: "deepinfra"
    aggregator: True
  - name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
    api: "deepinfra"
  - name: "google/gemma-2-9b-it"
    api: "deepinfra"
  - name: "microsoft/WizardLM-2-7B"
    api: "deepinfra"        

